[custom]
;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

#配置只针对OpenClash的配置，绕过大陆或不绕过
#规则匹配从上到下,顺序依次是本地网络直连&自定义→去广告拦截→国内域名与IP+兜底走代理😀
#要防止DNS泄露，在去广告规则里面不能有DNS解析的操作，否则会去解析DNS匹配IP规则

;设置规则标志位
#本地网络&自定义规则
#ruleset=🎯 全球直连,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/MyCN.list

#需要优先匹配的规则
#微软 ChatGPT&Google合并
ruleset=🎊 GG,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/AI.list
ruleset=🎊 GG,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/Google.list
ruleset=🎵 Media,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/ProxyMedia.list
ruleset=✨ 微软服务,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/Microsoft.list

#GFWLIST需要自己修改 
ruleset=🚀 节点选择,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/ProxyGFWlist.list
ruleset=☘️ 🇸🇬 狮城,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/ProxyDNS.list
#Apple Servcies
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/Apple.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/Rules/ChinaDomain.list

;ruleset=🎯 全球直连,[]GEOIP,LAN
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
#未命中规则
ruleset=🐳 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国`[]DIRECT`.*
custom_proxy_group=🎊 GG`select`[]🚀 节点选择`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW)
custom_proxy_group=🎵 Media`select`[]🚀 节点选择`[]DIRECT`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国`.*
custom_proxy_group=✨ 微软服务`select`[]🚀 节点选择`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW|香港|HK|🇭🇰|Hong Kong|HongKong|hongkong)`[]DIRECT
#微软服务使用节点选择、狮城、美国、正则筛选节点分离出来、直连
#custom_proxy_group=❄️ Google`select`[]🚀 节点选择`[]☘️ 🇸🇬 狮城`[]🎊 ChatGPT`[]🌎 🇺🇸 美国`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW)
#Google服务使用节点选择、狮城、美国、正则筛选节点分离出来、直连
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
#custom_proxy_group=🍃 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🐳 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]☘️ 🇸🇬 狮城`[]🌎 🇺🇸 美国
custom_proxy_group=☘️ 🇸🇬 狮城`url-test`(新加坡|SG|狮|🇸🇬|Singapore)`http://cp.cloudflare.com/`500,2,50
custom_proxy_group=🌎 🇺🇸 美国`url-test`(美国|🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/`500,2,50

#custom_proxy_group=♻️ 🇭🇰 香港`url-test`(香港|HK|🇭🇰|Hong Kong|HongKong|hongkong)`http://www.apple.com/library/test/success.html`500,2,50
#custom_proxy_group=💫 🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.apple.com/library/test/success.html`500,2,50
#custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`1800,5,300  超时时间1800ms，测试5次，节点时间差超过50ms 切换节点
#http://cp.cloudflare.com/  http://www.msftconnecttest.com/connecttest.txt  http://www.google.com/generate_204 http://www.apple.com/library/test/success.html http://www.gstatic.com/generate_204
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
#💫🎊🏅🔮🌟🌠❄️🌱☘️🦴🐕🐳🌈🔥📺📢🔔♻️🏳️‍🌈⚧️🪟✨🐝🎯🛡️📹🚀✨🎋🪖🧩🧱🛡️🔎🔍🚩🌏🌍🌎🌀🎶🎵
;luck
