[custom]
;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
#规则匹配从上到下,顺序依次是本地网络直连&自定义→去广告拦截→国内域名与IP+兜底走代理😀
#要防止DNS泄露，在去广告规则里面不能有DNS解析的操作，否则会去解析DNS匹配IP规则

#💫🎊🏅🔮🌟🌠❄️🌱☘️🦴🐕🐳🌈🔥📺📢🔔♻️🏳️‍🌈⚧️🪟✨🐝🎯🛡️📹🚀✨🎋🪖🧩🧱🛡️🔎🔍🚩🌏🌍🌎🌀🎶🎵🤖🎞️💎🎯♥️🎸⚧️💻🎬🎥📺🚨🪟❄️🔯✡️🚀🎉🎇🛩️✈️🚀
;luck

[custom]

clash_rule_base=https://raw.githubusercontent.com/yootor/ACL4SSR/master/Clash/config/Openwrt_Base.yaml

#规则配置开关
enable_rule_generator=false
overwrite_original_rules=false

;设置分组标志位
custom_proxy_group=🚀 Select`select`[]🎊 🇭🇰 HongKong`[]🌎 🇺🇸 USA`[]☘️ 🇸🇬 Singapore`[]DIRECT`.*
custom_proxy_group=🤖 GG`select`[]🚀 Select`[]🌎 🇺🇸 USA`[]☘️ 🇸🇬 Singapore`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW)
custom_proxy_group=📺 Media`select`[]🚀 Select`[]🎊 🇭🇰 HongKong`[]☘️ 🇸🇬 Singapore`[]🌎 🇺🇸 USA`.*
custom_proxy_group=✨ Microsoft`select`[]🚀 Select`[]🎊 🇭🇰 HongKong`[]☘️ 🇸🇬 Singapore`[]🌎 🇺🇸 USA`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW|香港|HK|🇭🇰|Hong Kong|HongKong|hongkong)`[]DIRECT
#微软服务使用节点选择、狮城、美国、正则筛选节点分离出来、直连
#custom_proxy_group=❄️ Google`select`[]🚀 Select`[]🎊 🇭🇰 HongKong`[]🎊 ChatGPT`[]🌎 🇺🇸 USA`(Singapore|新加坡|SG|狮|🇸🇬|美|US|🇺🇸|台|新北|彰化|Taiwan|🇨🇳|TW)
#Google服务使用节点选择、狮城、美国、正则筛选节点分离出来、直连
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Select`[]🎊 🇭🇰 HongKong`[]🌎 🇺🇸 USA
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🚀 Select
#使用MOSDNS 去广告，屏蔽Clash的广告规则
#custom_proxy_group=🍃 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🐳 Final`select`[]🚀 Select`[]DIRECT`[]🎊 🇭🇰 HongKong`[]☘️ 🇸🇬 Singapore`[]🌎 🇺🇸 USA
custom_proxy_group=🎊 🇭🇰 HongKong`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`https://cp.cloudflare.com/generate_204`500,2,50
custom_proxy_group=☘️ 🇸🇬 Singapore`url-test`(新加坡|SG|狮|🇸🇬|Singapore)`https://cp.cloudflare.com/generate_204`500,2,50
custom_proxy_group=🌎 🇺🇸 USA`url-test`(美国|🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`https://cp.cloudflare.com/generate_204`500,2,50


;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
#💫🎊🏅🔮🌟🌠❄️🌱☘️🦴🐕🐳🌈🔥📺📢🔔♻️🏳️‍🌈⚧️🪟✨🐝🎯🛡️📹🚀✨🎋🪖🧩🧱🛡️🔎🔍🚩🌏🌍🌎🌀🎶🎵🤖🎞️💎🎯♥️🎸⚧️💻🎬🎥📺🚨🪟❄️🔯✡️🚀🎉🎇🛩️✈️🚀
;luck
